name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      SLN_LOCATION: ./Pathway.sln
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore $SLN_LOCATION
    - name: Build
      run: dotnet build --no-restore $SLN_LOCATION
    - name: Test
      run: dotnet test --no-build --verbosity normal $SLN_LOCATION
